### ISSUE TITLE
MarkupView element isn't auto-expanded

### ISSUE THREAD

**Issue by janodvarko** [firebug/firequery#29]
MarkupView element isn't auto-expanded when the user clicks a link from within jQuery.data tooltip displayed inside the Inspector panel.

STR:

1) Load http://softwareishard.com/temp/firequery/test1/index.html
2) Select the Inspector panel and find "div.doc" element. Click on associated envelop icon.
3) Expand the 'test' object and click on "div#test-div" element (on the value)
4) The element is supposed to be selected in the Inspector panel, but it isn't because it's not directly visible and auto-expanding of its parent element doesn't work

You can try clicking on "body#content" (again the value), the body element is properly selected in the MarkupView since it's visible (?).

Platform support might be needed.

Here is the related piece of code that does the auto-selection of given node.
https://github.com/firebug/firequery/blob/de49a7f0a971ad0653670056fe07174ab1e7ce00/lib/data-tooltip.js#L153
(look for 'onNavigate' method)

Honza

**Comment by janodvarko** [comment]
@captainbrosset: any tips what could be wrong here?

(I know you need a rest atm, so reply as soon as you are back on your feet :-)

Honza

**Comment by captainbrosset** [comment]
I think the code you have in onNavigate is unnecessarily complex and probably buggy in that it doesn't expands the parent nodes and wait for the various promises involved in that process to resolve.
There's a simpler way to achieve this: `inspector.selection.setNodeFront`.

For instance, if I open the page you linked to, then I open the inspector (making sure only `<body>` is selected and `#test-div` is hidden), then I can simulate what you're trying to do from scratchpad:
- open scratchpad
- switch it to Browser mode
- enter the following code and run it:

```
let i = [...gDevTools._toolboxes][0][1].getPanel("inspector");
i.walker.querySelector(i.walker.rootNode, "#test-div").then(node => {
  i.selection.setNodeFront(node, "selectorsearch");
});
```

This ends up selecting `#test-div` correctly, with all parents expanded.
Note that `[...gDevTools._toolboxes][0][1]` is just a way I use in the global scratchpad environment to get a reference to the `toolbox` instance. In `data-tooltip.js` you seem to have access to both `this.toolbox` and `this.markup`, so you could either do `this.toolbox.getPanel("inspector")` or `this.markup.inspector`.

**Comment by janodvarko** [comment]
@captainbrosset thanks! When I try your solution (that also involves querySelector) it works well.

There seems to be yet another problem since the way I am getting the nodeFront from the backend is different and doesn't work.

I am using getNode(actorid) that is implemented on the backend and looks like as follows:
https://github.com/firebug/firequery/blob/1bd63d06222bfd815dd30abecda387ff067d3a9b/lib/firequery-actor.js#L391

```
let walkerActor = this.conn.getActor(this.walkerActorID);
return walkerActor.getNodeActorFromObjectActor(actorId);
```

When passing the received nodeFront to this.panel.selection.setFront() parent elements are not auto expanded.

The only difference between the front returned by queryElement and (my) getNode (I know about) is that my front doesn't have _parent properly set. That could be the issue no?

What could be wrong with my getNode()?

Honza

**Comment by captainbrosset** [comment]
> The only difference between the front returned by queryElement and (my) getNode (I know about) is that my front doesn't have _parent properly set. That could be the issue no?

Yes totally. I think what's happening is for some reasons the chain of unknown parents leading from the `#test-div` node to one of the ancestor nodes we know about in the markup-view is not sent via the protocol.

To make this clearer, the UI of the markup-view only knows about the Nodes that are currently being displayed. It only has a partial knowledge of the DOM tree, and it acquires more knowledge about it when you expand nodes for example.
Thats's why a lot of WalkerActor methods return not only the NodeActor you expect it to return but also the chain of parents that leads up to the last point the UI knows about.
Even if on the front side we filter these out (in a `protocol.custom` method interceptor) to only return the node we care about, transferring them over the wire makes sure protocol.js knows about them, and registers them as actors that it can access later.

So, later, when you need to select a deep nested node, it can look at its parents and expand them first.

What's weird is that your `getNode` method just returns what `getNodeActorFromObjectActor` returns, which is the right type (`disconnectedNode` which is the node and the new parents).

I think the problem is that the response sent by getNode doesn't end up being treated by the WalkerFront, and therefore the parenting process isn't being executed. The `_parent` property is being initialized in `NodeFront.form`, when `reparent` is called. So maybe the `form` method isn't called at all.
This goes a bit beyond what I know from protocol.js off the top of my head, so I'd have to debug to learn more here, but unfortunately don't have the time just now. Can you investigate a bit more in depth here?

**Comment by janodvarko** [comment]
> This goes a bit beyond what I know from protocol.js off the top of my head, so I'd have to debug to learn more here, but unfortunately don't have the time just now. Can you investigate a bit more in depth here?

Sure!

Problem found, FireQueryFront.ensureParentFront() impl was wrong (missing return value)

Thanks for the help Patrick!

Honza
